sudo: required
services:
  - docker

before_install:
  - docker build -t robclayton/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run robclayton/react-test npm test -- --coverage

after_success:
  - docker build -t robclayton/multi-client ./client
  - docker build -t robclayton/multi-nginx ./nginx
  - docker build -t robclayton/multi-server ./server
  - docker build -t robclayton/multi-worker ./worker
  # Log in to the docker CLI
  # Note: ENV vars set at travis-cli.org
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and deploy to docker hub:
  - docker push robclayton/multi-client
  - docker push robclayton/multi-nginx
  - docker push robclayton/multi-server
  - docker push robclayton/multi-worker
